# Generated by Django 3.2.9 on 2023-04-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_feed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/staff')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.IntegerField(default=0)),
                ('post', models.CharField(max_length=100)),
                ('interest_area_1', models.CharField(max_length=100)),
                ('interest_area_2', models.CharField(max_length=100)),
                ('joined_year', models.IntegerField(default=0)),
            ],
        ),
    ]
