# Generated by Django 3.2.9 on 2023-04-19 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='type',
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
