# Generated by Django 3.2.9 on 2023-04-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230419_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_type',
            new_name='type',
        ),
    ]
